name: build opencv nodejs bindings
run-name: build opencv nodejs bindings
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Brew Install Cmake Opencv
        run: |
          brew install cmake
          brew install opencv@4
          export OPENCV4NODEJS_DISABLE_AUTOBUILD=1
          export OPENCV_LIB_DIR=/opt/homebrew/Cellar/opencv/4.7.0_1/lib
          export OPENCV_BIN_DIR=/opt/homebrew/Cellar/opencv/4.7.0_1/bin
          export OPENCV_INCLUDE_DIR=/opt/homebrew/Cellar/opencv/4.7.0_1/include/opencv4
      - name: Copy opencv2 includes
        run: cp -R /opt/homebrew/Cellar/opencv/4.7.0_1/include/opencv4/opencv2 /usr/local/include
      - name: Install
        run: npm install
      - name: Install node-gyp
        run: npm install -g node-gyp 
      - name: Configure node-gyp
        run: |
          cd node_modules/@u4/opencv4nodejs
          node-gyp configure
          cd ../../../
      - name: Build m1
        run: npm run install_arm64
      - name: Upload build files
        uses: hujiulong/action-qiniu-upload@master
        with:
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          bucket: ${{ secrets.QINIU_BUCKET }}
          source_dir: "node_modules/@u4/opencv4nodejs"
          dest_dir: "/opencv4nodejs"
          ignore_source_map: true
